//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutbreakSurvivor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OutbreakSurvivor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduces energy by an additional point each turn..
        /// </summary>
        internal static string DiseaseAnthraxDescription {
            get {
                return ResourceManager.GetString("DiseaseAnthraxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anthrax.
        /// </summary>
        internal static string DiseaseAnthraxName {
            get {
                return ResourceManager.GetString("DiseaseAnthraxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduces energy by 3 additional points each turn..
        /// </summary>
        internal static string DiseaseCholeraDescription {
            get {
                return ResourceManager.GetString("DiseaseCholeraDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cholera.
        /// </summary>
        internal static string DiseaseCholeraName {
            get {
                return ResourceManager.GetString("DiseaseCholeraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants immunity to Tuberculosis, but reduces the resistance to Cholera by 50% each turn..
        /// </summary>
        internal static string DiseaseDiphtheriaDescription {
            get {
                return ResourceManager.GetString("DiseaseDiphtheriaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diphtheria.
        /// </summary>
        internal static string DiseaseDiphtheriaName {
            get {
                return ResourceManager.GetString("DiseaseDiphtheriaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spread Radius.
        /// </summary>
        internal static string DiseaseRadiusText {
            get {
                return ResourceManager.GetString("DiseaseRadiusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduces the resistance to Anthrax by 10% each turn..
        /// </summary>
        internal static string DiseaseRubeolaDescription {
            get {
                return ResourceManager.GetString("DiseaseRubeolaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubeola.
        /// </summary>
        internal static string DiseaseRubeolaName {
            get {
                return ResourceManager.GetString("DiseaseRubeolaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduces energy by 2 additional points each turn..
        /// </summary>
        internal static string DiseaseTuberculosisDescription {
            get {
                return ResourceManager.GetString("DiseaseTuberculosisDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuberculosis.
        /// </summary>
        internal static string DiseaseTuberculosisName {
            get {
                return ResourceManager.GetString("DiseaseTuberculosisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases resistance to Rubeola by 20% each turn, but reduces resistance to Tuberculosis by 20% each turn..
        /// </summary>
        internal static string DiseaseVeganitisDescription {
            get {
                return ResourceManager.GetString("DiseaseVeganitisDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veganitis.
        /// </summary>
        internal static string DiseaseVeganitisName {
            get {
                return ResourceManager.GetString("DiseaseVeganitisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Population:.
        /// </summary>
        internal static string EndGameInitialPopulationLabel {
            get {
                return ResourceManager.GetString("EndGameInitialPopulationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New game.
        /// </summary>
        internal static string EndGameOkButton {
            get {
                return ResourceManager.GetString("EndGameOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbreaks:.
        /// </summary>
        internal static string EndGameOutbreaksLabel {
            get {
                return ResourceManager.GetString("EndGameOutbreaksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string EndGameQuitButton {
            get {
                return ResourceManager.GetString("EndGameQuitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score:.
        /// </summary>
        internal static string EndGameScoreLabel {
            get {
                return ResourceManager.GetString("EndGameScoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Over.
        /// </summary>
        internal static string EndGameTitle {
            get {
                return ResourceManager.GetString("EndGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns:.
        /// </summary>
        internal static string EndGameTurnsLabel {
            get {
                return ResourceManager.GetString("EndGameTurnsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        internal static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy is reduced by 1 each turn. When Energy reaches 0, the individual dies..
        /// </summary>
        internal static string EnergyDescription {
            get {
                return ResourceManager.GetString("EnergyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mature.
        /// </summary>
        internal static string Maturity {
            get {
                return ResourceManager.GetString("Maturity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines whether this individual is old enough to reproduce..
        /// </summary>
        internal static string MaturityDescription {
            get {
                return ResourceManager.GetString("MaturityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population:.
        /// </summary>
        internal static string NewGameInitialPopulationLabel {
            get {
                return ResourceManager.GetString("NewGameInitialPopulationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start game.
        /// </summary>
        internal static string NewGameOkButton {
            get {
                return ResourceManager.GetString("NewGameOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string NewGameQuitButton {
            get {
                return ResourceManager.GetString("NewGameQuitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Size:.
        /// </summary>
        internal static string NewGameSizeLabel {
            get {
                return ResourceManager.GetString("NewGameSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        internal static string NewGameTitle {
            get {
                return ResourceManager.GetString("NewGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reproducability.
        /// </summary>
        internal static string Reproducability {
            get {
                return ResourceManager.GetString("Reproducability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reproducability determines the likelihood of passing on genes to children..
        /// </summary>
        internal static string ReproducabilityDescription {
            get {
                return ResourceManager.GetString("ReproducabilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reproduce.
        /// </summary>
        internal static string Reproduce {
            get {
                return ResourceManager.GetString("Reproduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  left this turn.
        /// </summary>
        internal static string ReproduceLeft {
            get {
                return ResourceManager.GetString("ReproduceLeft", resourceCulture);
            }
        }
    }
}
